### ISSUE TITLE
Typo in config_2017.cmd

### ISSUE THREAD

**Issue by metal-crow** [DGA-MI-SSI/YaCo#12] opened 2017-07-04 02:33 UTC
The build file `configure_2017.cmd` specifies the target as "Visual Studio 15 2017", which is not a valid target. Changing to "Visual Studio 15" fixes the error.

**Comment by bamiaux** [comment] 2017-07-05 06:28
Which version of cmake are you using ?
I cannot reproduce it
```
λ cmake --version
cmake version 3.8.2

λ cmake --help
The following generators are available on this platform:
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
```

**Comment by metal-crow** [comment] 2017-07-05 23:39
Using version 3.7.0, so i suppose 3.8 has changed the name of the generator. That's an unfortunate change, but i guess the build file is valid then.

**Comment by bamiaux** [comment] 2017-07-06 05:40
Ok, I'll close this bug
Anyway the various configure commands are just helpers, many people invoke cmake manually

**Closed by bamiaux** 2017-07-06 05:40 UTC
