### ISSUE TITLE
IDA slow/hang on save

### ISSUE THREAD

**Issue by paulsapps** [DGA-MI-SSI/YaCo#36] opened 2018-06-12 21:05 UTC
I don't know if this is a limitation or bug so I figured I'd raise it.

My repo is here:

https://github.com/AliveTeam/YaCo

Fork make a change and save to repro. IDA will hang for up to 20+ seconds on save.

**Comment by bamiaux** [comment] 2018-06-13 06:41
You may experience slowness if you initialized YaCo on a repo before the first auto-analysis was complete. You should probably do one force push to clear it up.
Anyway, the branch here https://github.com/DGA-MI-SSI/YaCo/tree/issue_36 may reduce the pauses

**Comment by paulsapps** [comment] 2018-06-13 12:01
That wasn't the case but I did a resync & force push anyway :).

Is there an automated build of that branch that I can try? After the force resync the delay is still around the same (not using the issue_36 branch).

**Comment by paulsapps** [comment] 2018-06-13 13:42
Managed to get a build but it still hangs IDA for around 20 seconds on save.

The output was this:

repo: commit: 4 added 1 updated 0 deleted

And the changes where:

https://github.com/AliveTeam/YaCo/commit/33ffa2f346de5fdf821c60d8b3db8bf5097b0b81

**Comment by bamiaux** [comment] 2018-06-13 16:44
Sorry, I cannot do automated builds because this plugin need to compile against the IDA SDK which is not public.

About the slowness, there are multiple issues

* Saving may be slow when we need to commit too many files at once. If you save & you get hundred of committed files, it's slow. Version 2.0 mitigates this and the issue_36 further more, but all users need to use the latest version. IDA makes it hard to determine which events are useful & which events are high priority

* As you share your incremental changes to other people, the cache will grow in size. Sometimes when you save, we need to rebase your work on top of remote changes. Due to a current design limitation, we need to reload the whole cache directory in memory to correctly identify dependencies. This part is slow if your cache is big and if you do not use an SSD

For now, I advise switching every users to this branch, do a force push and maybe invest in a SSD or try it inside a ramdisk ^^

**Comment by paulsapps** [comment] 2018-06-13 20:19
Thanks, it is running in an SSD so I guess ram disk is the next thing to try. What is the min version of IDA that v2.0 requires? I will switch to this if we all have a compatible version.

**Comment by bamiaux** [comment] 2018-06-13 21:16
Ok, I’m using 7.1 and I’m not reproducing the 20s slowdown with the patches on top of v2.0
If you compile the binaries yourself, You should try with ida 7.1 and idasdk 7.1
Forget the RAM disk if you already have an ssd.

**Comment by paulsapps** [comment] 2018-06-13 21:31
OK - if mixed IDA versions use the same repo is that supported or will all users have to switch?

**Comment by devnoname120** [comment] 2018-06-15 17:17
> Sorry, I cannot do automated builds because this plugin need to compile against the IDA SDK which is not public.

@bamiaux 

Can't you host the IDA SDK somewhere with authentication required, and then you encrypt your credentials using [Travis CI's encrypted values feature?](https://docs.travis-ci.com/user/encryption-keys/)?

**Comment by bamiaux** [comment] 2018-06-16 12:03
The repository format is the same & compatible between 7.0 & 7.1
I don't know why you still have slowdowns, I need to check further

**Comment by bamiaux** [comment] 2018-06-16 12:06
@devnoname120 Sorry, I prefer to wait until hexrays make their SDK downloadable by anyone

**Comment by devnoname120** [comment] 2018-06-16 14:03
@bamiaux Do they plan to do so? I haven't read anything about it, and Hex-Rays isn't exactly known for making sound business decisions.

**Comment by paulsapps** [comment] 2018-06-18 07:13
Is there any logging or something I could enable that would help to track down the slow down source?

**Comment by bamiaux** [comment] 2018-06-18 16:19
@devnoname120 I have no idea about their plans, it's still a mystery to me why the SDK is not public

@paulsapps yes, set LOG_IDB_EVENTS to true here
https://github.com/DGA-MI-SSI/YaCo/blob/d9f6a60b78a4a446acc08357b2a56bfc7e3f3927/YaLibs/YaToolsIDALib/Hooks.cpp#L38
you will see some logs on IDA actions

**Comment by bamiaux** [comment] 2018-06-18 17:08
Note that if you plan to systematically document the whole base, or "as much as possible", it won't work, as the current XML file format is too inefficient to be able to duplicate a whole IDB

**Comment by paulsapps** [comment] 2018-06-20 07:07
I force pushed and flattened repo history to 1 commit. This has reduced save time from 20-40 seconds to about 5 seconds. This seems strange as I thought the force push would have had the same effect as it updates the "base" IDB file to the current "local" IDB file?

Perhaps that is a separate issue.

So with 1 new base IDB and no changes pressing save takes around 5 seconds and nothing gets pushed. Does that seem about on par with the kind of performance you would expect?

**Comment by bamiaux** [comment] 2018-06-24 17:29
What do you mean about the save time ? Maybe there's an issue here.

It takes 2s here, but I'm using a local remote. You can try with this
```
git remote rm origin
git clone . --bare /some/ssd/path
git remote add origin /some/ssd/path
```
It will remove the network overhead.
In any case, it seems saving does too many git commands which may be optimized, I'll look into it soon
Saving without any conflict should be faster than current version

**Comment by paulsapps** [comment] 2018-06-30 12:32
Confirmed its around 2 seconds with a local remote. So therefore the delay must be in huge network overhead? This is odd because if I push the changes from the local to real remote origin it only takes around 2 seconds. Therefore I would expect the over all time to be around 4 seconds?

**Comment by bamiaux** [comment] 2018-07-03 19:16
With current version, it looks like the biggest slowdown is during push, which entirely handled by libgit2.
I've updated to the latest version, but the changelog doesn't mention any speed change.
I've made some changes to rebasing which should be slightly faster than before but I don't expect dramatic changes

**Comment by bamiaux** [comment] 2018-07-13 17:18
Please try https://github.com/DGA-MI-SSI/YaCo/tree/git_async
Saving should be much faster as git push is done in the background now
Note that I didn't test it on linux, it may have build issues

**Comment by bamiaux** [comment] 2018-07-15 08:11
Linux build fixed

**Comment by paulsapps** [comment] 2018-07-16 19:43
Will get a Windows build and try it out as soon as, thanks :)

**Comment by paulsapps** [comment] 2018-07-17 18:57
Haven't used it too much yet but looks like the hang is reduced to 2-5 seconds which is acceptable by me :+1:

**Comment by bamiaux** [comment] 2018-07-19 19:13
I'm closing it, it's in master with other fixes and will be in the next release

**Closed by bamiaux** 2018-07-19 19:13 UTC
